# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-22 23:28
from __future__ import unicode_literals

from django.db import migrations, models
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='img',
            field=models.ImageField(upload_to=website.models.file_name),
        ),
    ]
