# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 04:21
from __future__ import unicode_literals

from django.db import migrations
import django_resized.forms
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_auto_20160822_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='img',
            field=django_resized.forms.ResizedImageField(upload_to=website.models.file_name),
        ),
    ]
