# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-23 05:02
from __future__ import unicode_literals

from django.db import migrations, models
import django_resized.forms
import website.models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20160823_0421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='date',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='img',
            field=django_resized.forms.ResizedImageField(upload_to=website.models.file_name, verbose_name='Imagen'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='location',
            field=models.CharField(max_length=100, verbose_name='Lugar'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Titulo'),
        ),
    ]
